#!/usr/bin/env node

const {uploadPackages} = require('../tools');

uploadPackages([
  {
    name: 'lib',
    version: '1.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: lib 1.0.0\\npwd: `pwd`\\n--"'
    }
  },
  {
    name: 'lib',
    version: '2.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: lib 2.0.0\\npwd: `pwd`\\n--"'
    }
  },
  {
    name: 'a',
    version: '1.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: a\\npwd: `pwd`\\n--"'
    },
    dependencies: {
      lib: '1.0.0'
    }
  },
  {
    name: 'b',
    version: '1.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: b\\npwd: `pwd`\\n--"'
    },
    dependencies: {
      lib: '2.0.0'
    }
  },
  {
    name: 'c',
    version: '1.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: b\\npwd: `pwd`\\n--"'
    },
    dependencies: {
      lib: '2.0.0'
    }
  },
  {
    name: 'd',
    version: '1.0.0',
    scripts: {
      postinstall: 'echo "postinstall of the package: c\\npwd: `pwd`\\n--"'
    }
  }
]);
