#!/usr/bin/env node

const {uploadPackages, uploadPackagesFromLocations} = require('../tools');

uploadPackages([
  {name: 'lib', version: '1.1.1'}
]);

uploadPackagesFromLocations([
  `${__dirname}/a`
]);

console.log('\nThe first part of the prepare script finished. Start the demo and press `enter` to run the second part');
process.stdin.once('data', () => {
  uploadPackages([
    {name: 'lib', version: '2.0.0'}
  ], false);
  process.exit();
});
