#!/usr/bin/env node

/*
DEMO:
 - run this script
 - run `npm install` under ./app
 - find all the instances of `lib` and explain what happened
*/


const {uploadPackages} = require('../tools');

uploadPackages([
  {name: 'lib', version: '1.1.1'},
  {name: 'lib', version: '2.2.2'},
  {name: 'a', version: '1.0.0', dependencies: {lib: '1.1.1'}},
  {name: 'b', version: '1.0.0', dependencies: {lib: '2.2.2'}}
]);
